- platform: flux
  lights:
    - light.wohnzimmer_klein
    - light.wohnzimmer_gross
  name: Flux
  start_time: '10:00'
  stop_time: '22:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  disable_brightness_adjust: true
  mode: xy
  transition: 30
