- platform: template
  switches:
    guests:
      value_template: '{{ states("input_boolean.guests") }}'
      friendly_name: 'Gast Modus'
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.guests
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.guests
