- platform: template
  switches:
    homeoffice:
      value_template: '{{ states("input_boolean.homeoffice") }}'
      friendly_name: 'Home Office'
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.homeoffice
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.homeoffice
