- platform: template
  switches:
    guests:
      value_template: '{{ states("input_boolean.lightmode") }}'
      friendly_name: 'Light Mode'
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.lightmode
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.lightmode
