- platform: template
  switches:
    partyguests:
      value_template: '{{ states("input_boolean.partyguests") }}'
      friendly_name: 'Party Gast Modus'
      turn_on:
        - service: input_boolean.turn_on
          entity_id: input_boolean.partyguests
      turn_off:
        - service: input_boolean.turn_off
          entity_id: input_boolean.partyguests
