homeassistant:
  customize: !include customize.yaml

alarm_control_panel: !include alarm.yaml
alexa: !include alexa.yaml
api:
automation: !include_dir_merge_list automations/
binary_sensor: !include binary_sensor.yaml
breaking_changes:
bmw_connected_drive: !include bmw.yaml
circadian_lighting: !include circadian_lighting.yaml
default_config:
device_tracker: !include_dir_merge_list devices/
discovery: #!include discovery.yaml
fan: !include_dir_merge_list fans/
frontend: !include frontend.yaml
group: !include_dir_merge_named groups/
hacs: !include hacs.yaml
http: !include http.yaml
history:
#homekit: !include homekit.yaml
input_boolean: !include_dir_named input_boolean/
input_number: !include_dir_named input_number/
input_select: !include_dir_named input_select/
logbook:
logger: !include logger.yaml
map:
media_player: !include_dir_merge_list mediaplayer/
mobile_app:
#mqtt: !include mqtt.yaml
notify: !include notify.yaml
person:
recorder: !include recorder.yaml
scene: !include_dir_merge_list scenes/
script: !include_dir_named scripts/
sensor: !include_dir_merge_list sensors/
shell_command: !include shell_commands.yaml
spotify: !include spotify.yaml
sun:
switch: !include_dir_merge_list switches/
system_health:
telegram_bot: !include telegram_bot.yaml
tts: !include tts.yaml
updater:
wake_on_lan: !include_dir_merge_list wol/
weather: !include weather.yaml
webostv: !include webostv.yaml
yeelight: !include yeelights.yaml
zone: !include zones.yaml
