homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml
  #  auth_providers:
  #    - type: legacy_api_password
  #      api_password: !secret http_password

alarm_control_panel: !include alarm.yaml
alexa: !include alexa.yaml
api:
automation: !include_dir_merge_list automations/
bmw_connected_drive: !include bmw.yaml
circadian_lighting: !include circadian_lighting.yaml
default_config:
device_tracker: !include_dir_merge_list devices/
discovery: !include discovery.yaml
fan: !include_dir_merge_list fans/
frontend: !include frontend.yaml
group: !include_dir_merge_named groups/
hacs: !include hacs.yaml
http: !include http.yaml
history:
input_boolean: !include_dir_named input_boolean/
input_number: !include_dir_named input_number/
input_select: !include_dir_named input_select/
logbook:
logger: !include logger.yaml
map:
media_player: !include_dir_merge_list mediaplayer/
mobile_app:
#mqtt: !include mqtt.yaml
notify: !include notify.yaml
panel_custom: !include_dir_merge_list panel_custom/
person:
#pi_hole: !include pihole.yaml
recorder: !include recorder.yaml
scene: !include_dir_merge_list scenes/
script: !include_dir_named scripts/
sensor: !include_dir_merge_list sensors/
shell_command: !include shell_commands.yaml
speedtestdotnet: !include speedtest.yaml
sun:
switch: !include_dir_merge_list switches/
system_health:
telegram_bot: !include telegram_bot.yaml
tts: !include tts.yaml
#unifi: !include unifi.yaml
updater:
vacuum: !include vacuum.yaml
wake_on_lan: !include_dir_merge_list wol/
weather: !include weather.yaml
#xiaomi_aqara: !include xiaomi_gateway.yaml
yeelight: !include yeelights.yaml
#zha: !include zha.yaml
zone: !include zones.yaml
