- alias: Lights turn off lights too bright
  trigger:
    platform: time_pattern
    minutes: '/1'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: switch.bett_led
      state: 'off'
    - condition: time
      after: '10:00'
      before: '20:00'
    - condition: numeric_state
      entity_id: sensor.airpurifier_illuminance
      above: 160
  action:
    - service: light.turn_off
      entity_id: group.wohnzimmer

- alias: Lights turn on too dark TV off
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: switch.bett_led
      state: 'off'
    - condition: time
      after: '11:00'
      before: '21:00'
    - condition: numeric_state
      entity_id: sensor.airpurifier_illuminance
      below: 50
    - condition: state
      entity_id: media_player.lg_oled
      state: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_normal

- alias: Light turn on too dark TV on
  trigger:
    - platform: time_pattern
      minutes: '/1'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: switch.bett_led
      state: 'off'
    - condition: time
      after: '11:00'
      before: '21:00'
    - condition: numeric_state
      entity_id: sensor.airpurifier_illuminance
      below: 50
    - condition: state
      entity_id: media_player.lg_oled
      state: 'on'
  action:
    - service: scene.turn_on
      entity_id: scene.wohnzimmer_dim

#- alias: Turn on small lamp after 20h
#  trigger:
#    platform: time_pattern
#    minutes: '/1'
#  condition:
#    - condition: state
#      entity_id: group.family
#      state: 'home'
#    - condition: state
#      entity_id: media_player.lg_oled
#      state: 'off'
#    - condition: state
#      entity_id: switch.bett_led
#      state: 'off'
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
#    - condition: state
#      entity_id: light.wohnzimmer_gross
#      state: 'on'
#  action:
#    - service: light.turn_on
#      entity_id: light.wohnzimmer_klein
