- alias: Lights Shield paused
  trigger:
    - platform: state
      entity_id: media_player.nvidia_shield
      from: 'playing'
      to: 'paused'
  condition:
    - condition: state
      entity_id: light.wohnzimmer_gross
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.wohnzimmer_normal

- alias: Lights Shield playing
  trigger:
    - platform: state
      entity_id: media_player.nvidia_shield
      to: 'playing'
      from: 'paused'
  condition:
    - condition: state
      entity_id: light.wohnzimmer_gross
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.wohnzimmer_dim
