- alias: Lights Shield paused
  trigger:
    - platform: state
      entity_id: media_player.nvidia_shield
      from: 'playing'
      to: 'paused'
  condition:
    - condition: state
      entity_id: light.wohnzimmer_gross
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.wohnzimmer_normal

- alias: Lights Shield playing
  trigger:
    - platform: state
      entity_id: media_player.nvidia_shield
      to: 'playing'
      from: 'paused'
  condition:
    - condition: state
      entity_id: light.wohnzimmer_gross
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.wohnzimmer_dim

- alias: Lights Media Source not HDMI1
  trigger:
    - platform: template
      value_template: "{{ is_state_attr('media_player.lg_oled', 'source', 'HDMI 2') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.lg_oled', 'source', 'HDMI 3') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.lg_oled', 'source', 'HDMI 4') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.lg_oled', 'source', 'Netflix') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.lg_oled', 'source', 'Live TV') }}"
    - platform: template
      value_template: "{{ is_state_attr('media_player.lg_oled', 'source', 'Youtube') }}"
  condition:
    - condition: state
      entity_id: light.wohnzimmer_gross
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.wohnzimmer_dim

