- platform: androidtv
  name: Nvidia Shield
#  device_class: androidtv
  host: 10.10.1.122
#  adb_server_ip: 127.0.0.1
#  adb_server_port: 5037
  adbkey: "/config/adbkey"
  apps:
    "com.netflix.ninja": "Netflix"
    "com.nvidia.tegrazone3": "NVIDIA Games"
    "com.google.android.tvlauncher": "Launcher"
    "com.amazon.amazonvideo.livingroom": "Amazon Prime"
    "com.google.android.youtube.tv": "Youtube"
    "com.plexapp.android": "Plex"
    "com.spotify.tv.android": "Spotify"
    "tv.twitch.android.app": "Twitch"

- platform: musiccast_yamaha
  host: 10.10.1.130
  port: 5009

