- platform: miflora
  mac: !secret miflora_1
  name: Chili Nora
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: !secret miflora_2
  name: Chili Reaper
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: !secret miflora_3
  name: Chili Purple
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery

- platform: miflora
  mac: !secret miflora_4
  name: Paprika
  monitored_conditions:
    - moisture
    - light
    - temperature
    - conductivity
    - battery
