- platform: pi_hole  
  host: !secret pi_url
  location: admin
  ssl: true
  verify_ssl: true
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - domains_being_blocked
    - queries_cached
    - queries_forwarded
    - unique_domains
    - clients_ever_seen
