- platform: unifigateway
  host: 127.0.0.1
  username: !secret unifi_username
  password: !secret unifi_password
  monitored_conditions:
    - www
    - lan
    - wan
    - wlan
    - alerts
    - firmware
