- platform: unifigateway
  host: unifi
  username: !secret unifi_username
  password: !secret unifi_password
  monitored_conditions:
    - www
    - lan
    - wan
    - wlan
    - alerts
    - firmware
