- platform: fritz
  host: 192.168.178.1
  username: !secret fritzbox_username
  password: !secret fritzbox_password
  interval_seconds: 10
  consider_home: 180
  new_device_defaults:
    track_new_devices: true
    hide_if_away: false
