- alias: 'Alarm niemand Zuhause'
  trigger:
    - platform: state
      entity_id: binary_sensor.entrydoor
      to: 'on'
    - platform: state
      entity_id: binary_sensor.balconywindow
      to: 'on'
    - platform: state
      entity_id: binary_sensor.balconydoor
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.alarm
      state: armed_away
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.alarm

- alias: 'Send notification when alarm triggered'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm
      to: 'triggered'
  action:
    - service: notify.notify_telegram_anon
      data:
        message: "ALARM!"
    - service: notify.notify_telegram_avo
      data:
        message: "ALARM!"
    - service: scene.turn_on
      entity_id: scene.alarm
