- alias: Bedtime
  trigger:
    - platform: state
      entity_id: switch.bett_led
      to: 'on'
      for:
        minutes: 2
    - platform: state
      entity_id: light.schlafzimmer_klein
      to: 'on'
      for:
        minutes: 2
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: switch.guests
      state: 'off'
    - condition: time
      after: '20:00'
      before: '00:00'
  action:
    - service: light.turn_off
      entity_id: group.wohnzimmer
    - service: media_player.turn_off
      entity_id: media_player.lg_oled
    - service: media_player.turn_on
      entity_id: media_player.firetv

- alias: Turn off bedroom
  trigger:
    platform: time
    at: '22:45'
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: switch.guests
      state: 'off'
    - condition: state
      entity_id: switch.bett_led
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.bett_led
    - service: light.turn_off
      entity_id: light.schlafzimmer_klein
