- alias: Avo Home
  trigger:
    platform: state
    entity_id: person.avo
    from: 'not_home'
    to: 'home'
  action:
    service: notify.notify_telegram_anon
    data:
      message: 'Avo ist Zuhause'

- alias: Avo not Home
  trigger:
    platform: state
    entity_id: person.avo
    from: 'home'
    to: 'not_home'
  action:
    service: notify.notify_telegram_anon
    data:
      message: 'Avo geht'

- alias: Door opened
  trigger:
    platform: state
    entity_id: binary_sensor.eingangsture
    to: 'on'
  condition:
    - condition: state
      entity_id: person.avo
      state: 'home'
    - condition: state
      entity_id: person.anon
      state: 'not_home'
  action:
    service: notify.notify_telegram_anon
    data:
      message: 'Tür geöffnet'
