- alias: Nobody home
  id: nobody_home
  trigger:
    platform: time_pattern
    minutes: '/5'
  condition:
#    - condition: state
#      entity_id: group.guests
#      state: 'not_home'
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: switch.turn_off
      entity_id: switch.bett_led
    - service: switch.turn_off
      entity_id: switch.tv_strom
    - service: switch.turn_off
      entity_id: switch.ladegerat
    - service: media_player.turn_off
      entity_id: media_player.lg_oled
    - service: media_player.turn_off
      entity_id: media_player.firetv
    - service: alarm_control_panel.alarm_arm_away
      data:
        entity_id: alarm_control_panel.alarm
        code: !secret alarm
