- alias: TV an
  trigger:
    platform: state
    entity_id: media_player.lg_oled
    to: 'on'
  condition:
    - condition: state
      entity_id: group.family
      state: 'not_home'
  action:
    - service: notify.notify_telegram_anon
      data:
        message: 'Die scheiß Blagen haben den Fernseher angemacht. Schalte aus.'
    - service: notify.notify_telegram_avo
      data:
        message: 'Die scheiß Blagen haben den Fernseher angemacht. Schalte aus.'
    - service: media_player.turn_off
      entity_id: media_player.lg_oled
