################################################################################
# Set input states when HA starts or states change
################################################################################

- alias: Set state for air purifier input
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.schlafzimmer_airpurifier_mode
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.schlafzimmer_airpurifier_mode
      option: '{{ states.fan.schlafzimmer_airpurifier.attributes.mode }}'

- alias: Set state for air purifier favorite level input
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: sensor.schlafzimmer_airpurifier_favorite_level
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.air_purifier_favorite_level
      value: '{{ states.fan.schlafzimmer_airpurifier.attributes.favorite_level | int }}'

################################################################################
# Inputs
################################################################################

- alias: Air purifier mode
  trigger:
    platform: state
    entity_id: input_select.xiaomi_air_purifier_mode
  action:
    - service: fan.set_speed
      data_template:
        entity_id: fan.schlafzimmer_airpurifier
        speed: '{{ states.input_select.xiaomi_air_purifier_mode.state }}'

- alias: Air purifier favorite level
  trigger:
    platform: state
    entity_id: input_number.xiaomi_air_purifier_favorite_level
  action:
    - service: xiaomi_miio.fan_set_favorite_level
      data_template:
        entity_id: fan.schlafzimmer_airpurifier
        level: '{{ states.input_number.xiaomi_air_purifier_favorite_level.state | int }}'


################################################################################
# Automatic control
################################################################################

- alias: Turn off airpurifier
  trigger:
    platform: numeric_state
    entity_id: fan.schlafzimmer_airpurifier
    value_template: "{{ states.fan.schlafzimmer_airpurifier.attributes.aqi | int }}"
    below: 50
    for: '00:00:10'
  condition:
    - condition: state
      entity_id: fan.schlafzimmer_airpurifier
      state: 'on'
  action:
    service: fan.turn_off
    entity_id: fan.schlafzimmer_airpurifier

- alias: Turn on airpurifier
  trigger:
    platform: numeric_state
    entity_id: fan.schlafzimmer_airpurifier
    value_template: "{{ states.fan.schlafzimmer_airpurifier.attributes.aqi | int }}"
    above: 50
    for: '00:00:10'
  condition:
    - condition: state
      entity_id: fan.schlafzimmer_airpurifier
      state: 'off'
  action:
    service: fan.turn_on
    entity_id: fan.schlafzimmer_airpurifier

- alias: Set favorite fan speed for airpurifier
  trigger:
    platform: time_pattern
    seconds: '/5'
  action:
    - service: fan.set_speed
      entity_id: fan.schlafzimmer_airpurifier
      data:
        speed: favorite
    - service: xiaomi_miio.fan_set_favorite_level
      data_template:
        entity_id: fan.schlafzimmer_airpurifier
        level: >
            {% if states.fan.schlafzimmer_airpurifier.attributes.aqi | int > 500 %}
              8
            {% elif states.fan.schlafzimmer_airpurifier.attributes.aqi | int > 400 %}
              7
            {% elif states.fan.schlafzimmer_airpurifier.attributes.aqi | int > 300 %}
              6
            {% elif states.fan.schlafzimmer_airpurifier.attributes.aqi | int > 250 %}
              5
            {% elif states.fan.schlafzimmer_airpurifier.attributes.aqi | int > 200 %}
              4
            {% elif states.fan.schlafzimmer_airpurifier.attributes.aqi | int > 150 %}
              3
            {% elif states.fan.schlafzimmer_airpurifier.attributes.aqi | int > 100 %}
              2
            {% elif states.fan.schlafzimmer_airpurifier.attributes.aqi | int > 50 %}
              1
            {% else %}
              0
            {% endif %}
    - service: input_select.select_option
      data_template:
        entity_id: input_select.xiaomi_air_purifier_mode
        option: '{{ states.fan.schlafzimmer_airpurifier.attributes.mode }}'
    - service: input_number.set_value
      data_template:
        entity_id: input_number.xiaomi_air_purifier_favorite_level
        value: '{{ states.fan.schlafzimmer_airpurifier.attributes.favorite_level }}'
