################################################################################
# Set input states when HA starts or states change
################################################################################

- alias: Set state for bedroom air purifier input
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.airpurifier_bedroom_mode
      option: '{{ states.fan.schlafzimmer_airpurifier.attributes.mode }}'

- alias: Set state for bedroom air purifier favorite level input
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: input_number.set_value
    data_template:
      entity_id: input_number.airpurifier_bedroom_favorite_level
      value: '{{ states.fan.schlafzimmer_airpurifier.attributes.favorite_level | int }}'

################################################################################
# Inputs
################################################################################

- alias: Livingroom air purifier mode
  trigger:
    platform: state
    entity_id: input_select.airpurifier_bedroom_mode
  action:
    - service: fan.set_preset_mode
      data_template:
        entity_id: fan.schlafzimmer_airpurifier
        preset_mode: '{{ states.input_select.airpurifier_mode.state }}'

################################################################################
# Automatic control
################################################################################

- alias: Turn off bedroom airpurifier
  trigger:
    platform: numeric_state
    entity_id: fan.schlafzimmer_airpurifier
    value_template: "{{ states('sensor.schlafzimmer_airpurifier_pm2_5') | int }}"
    below: 50
    for: '00:00:10'
  condition:
    - condition: state
      entity_id: fan.schlafzimmer_airpurifier
      state: 'on'
  action:
    service: fan.turn_off
    entity_id: fan.schlafzimmer_airpurifier

- alias: Turn on bedroom airpurifier
  trigger:
    platform: numeric_state
    entity_id: fan.schlafzimmer_airpurifier
    value_template: "{{ states('sensor.schlafzimmer_airpurifier_pm2_5') | int }}"
    above: 50
    for: '00:00:10'
  condition:
    - condition: state
      entity_id: fan.schlafzimmer_airpurifier
      state: 'off'
  action:
    service: fan.turn_on
    entity_id: fan.schlafzimmer_airpurifier

- alias: Set favorite fan speed for bedroom airpurifier
  trigger:
    platform: time_pattern
    seconds: '/30'
  action:
    - service: fan.set_preset_mode
      entity_id: fan.schlafzimmer_airpurifier
      data:
        preset_mode: Favorite
    - service: fan.set_percentage
      data_template:
        entity_id: fan.schlafzimmer_airpurifier
        percentage: >
            {% if states('sensor.schlafzimmer_airpurifier_pm2_5') | int == 600 %}
              100
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 500 %}
              90
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 400 %}
              80
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 350 %}
              70
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 300 %}
              60
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 230 %}
              50
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 150 %}
              40
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 125 %}
              30
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 100 %}
              20
            {% elif states('sensor.schlafzimmer_airpurifier_pm2_5') | int > 50 %}
              10
            {% else %}
              0
            {% endif %}
    - service: input_select.select_option
      data_template:
        entity_id: input_select.airpurifier_bedroom_mode
        option: "{{ states('fan.schlafzimmer_airpurifier.attributes.mode') }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.airpurifier_bedroom_favorite_level
        value: "{{ states('fan.schlafzimmer_airpurifier.attributes.favorite_level') }}"
