- alias: Lights FireTV paused
  trigger:
    - platform: state
      entity_id: media_player.firetv
      #from: 'playing'
      to: 'paused'
    - platform: state
      entity_id: media_player.firetv
      #from: 'playing'
      to: 'standby'
  condition:
    - condition: state
      entity_id: light.schlafzimmer_klein
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.schlafzimmer_normal

- alias: Lights FireTV playing
  trigger:
    - platform: state
      entity_id: media_player.firetv
      to: 'playing'
      #from: 'paused'
  condition:
    - condition: state
      entity_id: light.schlafzimmer_klein
      state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.schlafzimmer_dim

